name: Publish Packages
on:
    release:
        types: [created]
jobs:
    publish-npm:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3
            # Setup Bun, Install, Run Tests, Build
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: Install
              run: bun install
            - name: Build
              run: bun run build
            # Setup NPM - For Publishing
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            # Publish
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
